//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineHitssApi
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Historial
    {
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public int UserID { get; set; }
        [DataMember]
        public int CarteleraID { get; set; }
    
        public virtual Cartelera Cartelera { get; set; }
        public virtual User User { get; set; }
    }
}
