//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineHitss.CineHitssService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CineHitssApi")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pelicula", Namespace="http://schemas.datacontract.org/2004/07/CineHitssApi")]
    [System.SerializableAttribute()]
    public partial class Pelicula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClasificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DuracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GeneroIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinopsisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clasification {
            get {
                return this.ClasificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ClasificationField, value) != true)) {
                    this.ClasificationField = value;
                    this.RaisePropertyChanged("Clasification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duracion {
            get {
                return this.DuracionField;
            }
            set {
                if ((this.DuracionField.Equals(value) != true)) {
                    this.DuracionField = value;
                    this.RaisePropertyChanged("Duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GeneroID {
            get {
                return this.GeneroIDField;
            }
            set {
                if ((this.GeneroIDField.Equals(value) != true)) {
                    this.GeneroIDField = value;
                    this.RaisePropertyChanged("GeneroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinopsis {
            get {
                return this.SinopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SinopsisField, value) != true)) {
                    this.SinopsisField = value;
                    this.RaisePropertyChanged("Sinopsis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cartelera", Namespace="http://schemas.datacontract.org/2004/07/CineHitssApi")]
    [System.SerializableAttribute()]
    public partial class Cartelera : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeliculaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CineID {
            get {
                return this.CineIDField;
            }
            set {
                if ((this.CineIDField.Equals(value) != true)) {
                    this.CineIDField = value;
                    this.RaisePropertyChanged("CineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((this.HorarioField.Equals(value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeliculaID {
            get {
                return this.PeliculaIDField;
            }
            set {
                if ((this.PeliculaIDField.Equals(value) != true)) {
                    this.PeliculaIDField = value;
                    this.RaisePropertyChanged("PeliculaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cine", Namespace="http://schemas.datacontract.org/2004/07/CineHitssApi")]
    [System.SerializableAttribute()]
    public partial class Cine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiudadIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadID {
            get {
                return this.CiudadIDField;
            }
            set {
                if ((this.CiudadIDField.Equals(value) != true)) {
                    this.CiudadIDField = value;
                    this.RaisePropertyChanged("CiudadID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CineHitssService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        CineHitss.CineHitssService.User GetUser(string _Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.User> GetUserAsync(string _Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        CineHitss.CineHitssService.User LoginUser(string _Username, string _Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.User> LoginUserAsync(string _Username, string _Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPointsUser", ReplyAction="http://tempuri.org/IService1/AddPointsUserResponse")]
        string AddPointsUser(int _points, int _UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPointsUser", ReplyAction="http://tempuri.org/IService1/AddPointsUserResponse")]
        System.Threading.Tasks.Task<string> AddPointsUserAsync(int _points, int _UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPelicula", ReplyAction="http://tempuri.org/IService1/GetPeliculaResponse")]
        CineHitss.CineHitssService.Pelicula GetPelicula(string _peliculaName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPelicula", ReplyAction="http://tempuri.org/IService1/GetPeliculaResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.Pelicula> GetPeliculaAsync(string _peliculaName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPeliculasgen", ReplyAction="http://tempuri.org/IService1/GetPeliculasgenResponse")]
        CineHitss.CineHitssService.Pelicula[] GetPeliculasgen(string _genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPeliculasgen", ReplyAction="http://tempuri.org/IService1/GetPeliculasgenResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.Pelicula[]> GetPeliculasgenAsync(string _genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPeliculasClas", ReplyAction="http://tempuri.org/IService1/GetPeliculasClasResponse")]
        CineHitss.CineHitssService.Pelicula[] GetPeliculasClas(string _clasificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPeliculasClas", ReplyAction="http://tempuri.org/IService1/GetPeliculasClasResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.Pelicula[]> GetPeliculasClasAsync(string _clasificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPeliculasHorario", ReplyAction="http://tempuri.org/IService1/GetPeliculasHorarioResponse")]
        CineHitss.CineHitssService.Cartelera[] GetPeliculasHorario(System.DateTime _Dia, string _peliculaname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPeliculasHorario", ReplyAction="http://tempuri.org/IService1/GetPeliculasHorarioResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.Cartelera[]> GetPeliculasHorarioAsync(System.DateTime _Dia, string _peliculaname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCinesxCiudad", ReplyAction="http://tempuri.org/IService1/GetCinesxCiudadResponse")]
        CineHitss.CineHitssService.Cine[] GetCinesxCiudad(string _ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCinesxCiudad", ReplyAction="http://tempuri.org/IService1/GetCinesxCiudadResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.Cine[]> GetCinesxCiudadAsync(string _ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPeliculasxCine", ReplyAction="http://tempuri.org/IService1/GetPeliculasxCineResponse")]
        CineHitss.CineHitssService.Pelicula[] GetPeliculasxCine(string _location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPeliculasxCine", ReplyAction="http://tempuri.org/IService1/GetPeliculasxCineResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.Pelicula[]> GetPeliculasxCineAsync(string _location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HorariosPeliculas", ReplyAction="http://tempuri.org/IService1/HorariosPeliculasResponse")]
        CineHitss.CineHitssService.Cartelera[] HorariosPeliculas(string _peliculaname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HorariosPeliculas", ReplyAction="http://tempuri.org/IService1/HorariosPeliculasResponse")]
        System.Threading.Tasks.Task<CineHitss.CineHitssService.Cartelera[]> HorariosPeliculasAsync(string _peliculaname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CineHitss.CineHitssService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CineHitss.CineHitssService.IService1>, CineHitss.CineHitssService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineHitss.CineHitssService.User GetUser(string _Username) {
            return base.Channel.GetUser(_Username);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.User> GetUserAsync(string _Username) {
            return base.Channel.GetUserAsync(_Username);
        }
        
        public CineHitss.CineHitssService.User LoginUser(string _Username, string _Password) {
            return base.Channel.LoginUser(_Username, _Password);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.User> LoginUserAsync(string _Username, string _Password) {
            return base.Channel.LoginUserAsync(_Username, _Password);
        }
        
        public string AddPointsUser(int _points, int _UserId) {
            return base.Channel.AddPointsUser(_points, _UserId);
        }
        
        public System.Threading.Tasks.Task<string> AddPointsUserAsync(int _points, int _UserId) {
            return base.Channel.AddPointsUserAsync(_points, _UserId);
        }
        
        public CineHitss.CineHitssService.Pelicula GetPelicula(string _peliculaName) {
            return base.Channel.GetPelicula(_peliculaName);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.Pelicula> GetPeliculaAsync(string _peliculaName) {
            return base.Channel.GetPeliculaAsync(_peliculaName);
        }
        
        public CineHitss.CineHitssService.Pelicula[] GetPeliculasgen(string _genero) {
            return base.Channel.GetPeliculasgen(_genero);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.Pelicula[]> GetPeliculasgenAsync(string _genero) {
            return base.Channel.GetPeliculasgenAsync(_genero);
        }
        
        public CineHitss.CineHitssService.Pelicula[] GetPeliculasClas(string _clasificacion) {
            return base.Channel.GetPeliculasClas(_clasificacion);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.Pelicula[]> GetPeliculasClasAsync(string _clasificacion) {
            return base.Channel.GetPeliculasClasAsync(_clasificacion);
        }
        
        public CineHitss.CineHitssService.Cartelera[] GetPeliculasHorario(System.DateTime _Dia, string _peliculaname) {
            return base.Channel.GetPeliculasHorario(_Dia, _peliculaname);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.Cartelera[]> GetPeliculasHorarioAsync(System.DateTime _Dia, string _peliculaname) {
            return base.Channel.GetPeliculasHorarioAsync(_Dia, _peliculaname);
        }
        
        public CineHitss.CineHitssService.Cine[] GetCinesxCiudad(string _ciudad) {
            return base.Channel.GetCinesxCiudad(_ciudad);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.Cine[]> GetCinesxCiudadAsync(string _ciudad) {
            return base.Channel.GetCinesxCiudadAsync(_ciudad);
        }
        
        public CineHitss.CineHitssService.Pelicula[] GetPeliculasxCine(string _location) {
            return base.Channel.GetPeliculasxCine(_location);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.Pelicula[]> GetPeliculasxCineAsync(string _location) {
            return base.Channel.GetPeliculasxCineAsync(_location);
        }
        
        public CineHitss.CineHitssService.Cartelera[] HorariosPeliculas(string _peliculaname) {
            return base.Channel.HorariosPeliculas(_peliculaname);
        }
        
        public System.Threading.Tasks.Task<CineHitss.CineHitssService.Cartelera[]> HorariosPeliculasAsync(string _peliculaname) {
            return base.Channel.HorariosPeliculasAsync(_peliculaname);
        }
    }
}
