//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineHitss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartelera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cartelera()
        {
            this.Historials = new HashSet<Historial>();
        }
    
        public int id { get; set; }
        public System.DateTime Horario { get; set; }
        public int PeliculaID { get; set; }
        public int CineID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial> Historials { get; set; }
        public virtual Cine Cine { get; set; }
        public virtual Pelicula Pelicula { get; set; }
    }
}
